export const E3_EDITOR_ERROR = Object.freeze({
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNKNOWN_OPERATION: 'UNKNOWN_OPERATION',
  UNSUPPORTED_VERSION: 'UNSUPPORTED_VERSION',
  REQUEST_TOO_LARGE: 'REQUEST_TOO_LARGE',
  INVALID_PATH: 'INVALID_PATH',
  FORBIDDEN_PATH: 'FORBIDDEN_PATH',
  PATH_TAMPERED: 'PATH_TAMPERED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_EXISTS: 'FILE_EXISTS',
  NOT_REGULAR_FILE: 'NOT_REGULAR_FILE',
  NOT_DIRECTORY: 'NOT_DIRECTORY',
  SYMLINK_BLOCKED: 'SYMLINK_BLOCKED',
  HARDLINK_BLOCKED: 'HARDLINK_BLOCKED',
  BINARY_FILE_BLOCKED: 'BINARY_FILE_BLOCKED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  PREIMAGE_MISMATCH: 'PREIMAGE_MISMATCH',
  MATCH_COUNT_MISMATCH: 'MATCH_COUNT_MISMATCH',
  MOVE_SEMANTICS_MISMATCH: 'MOVE_SEMANTICS_MISMATCH',
  PREIMAGE_RETENTION_FAILED: 'PREIMAGE_RETENTION_FAILED',
  LEASE_REJECTED: 'LEASE_REJECTED'
})

export class E3EditorError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options)
    this.name = 'E3EditorError'
    this.code = code
    this.details = Object.freeze({ ...details })
  }
}
