export const E3_WORKSPACE_ERROR = Object.freeze({
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  UNSAFE_STORAGE_ROOT: 'UNSAFE_STORAGE_ROOT',
  UNSAFE_SOURCE_REPOSITORY: 'UNSAFE_SOURCE_REPOSITORY',
  UNSAFE_PATH: 'UNSAFE_PATH',
  PATH_TAMPERED: 'PATH_TAMPERED',
  LOCKED: 'LOCKED',
  LOCK_TAMPERED: 'LOCK_TAMPERED',
  GIT_FAILED: 'GIT_FAILED',
  MIRROR_UNSAFE: 'MIRROR_UNSAFE',
  COMMIT_NOT_FOUND: 'COMMIT_NOT_FOUND',
  COMMIT_UNREACHABLE: 'COMMIT_UNREACHABLE',
  INVALID_SESSION_STATE: 'INVALID_SESSION_STATE',
  LEASE_MISMATCH: 'LEASE_MISMATCH',
  WORKSPACE_EXISTS: 'WORKSPACE_EXISTS',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_RECORD_MISMATCH: 'WORKSPACE_RECORD_MISMATCH',
  MANIFEST_MISMATCH: 'MANIFEST_MISMATCH',
  SPECIAL_FILE_BLOCKED: 'SPECIAL_FILE_BLOCKED',
  CLEANUP_BLOCKED: 'CLEANUP_BLOCKED',
  PROVISIONING_ROLLBACK_FAILED: 'PROVISIONING_ROLLBACK_FAILED'
})

export class E3WorkspaceError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options)
    this.name = 'E3WorkspaceError'
    this.code = code
    this.details = Object.freeze({ ...details })
  }
}
