export const E3_PERSISTENCE_ERROR = Object.freeze({
  INVALID_DATABASE_PATH: 'INVALID_DATABASE_PATH',
  DATABASE_CONFIGURATION_FAILED: 'DATABASE_CONFIGURATION_FAILED',
  DATABASE_INTEGRITY_FAILED: 'DATABASE_INTEGRITY_FAILED',
  INVALID_MIGRATION_SET: 'INVALID_MIGRATION_SET',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  MIGRATION_CHECKSUM_MISMATCH: 'MIGRATION_CHECKSUM_MISMATCH',
  UNSUPPORTED_SCHEMA: 'UNSUPPORTED_SCHEMA',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  LEASE_NOT_FOUND: 'LEASE_NOT_FOUND',
  LEASE_CONFLICT: 'LEASE_CONFLICT',
  OPTIMISTIC_CONFLICT: 'OPTIMISTIC_CONFLICT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  OPERATION_REQUIRED: 'OPERATION_REQUIRED',
  INVALID_RECORD: 'INVALID_RECORD'
})

export class E3PersistenceError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options)
    this.name = 'E3PersistenceError'
    this.code = code
    this.details = Object.freeze({ ...details })
  }
}
