export const E3_RECOVERY_ERROR = Object.freeze({
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  INVALID_REQUEST: 'INVALID_REQUEST',
  CLEANUP_LEASE_REQUIRED: 'CLEANUP_LEASE_REQUIRED',
  CLEANUP_LEASE_MISMATCH: 'CLEANUP_LEASE_MISMATCH',
  CLEANUP_LEASE_EXPIRED: 'CLEANUP_LEASE_EXPIRED',
  REQUEST_REPLAY_CONFLICT: 'REQUEST_REPLAY_CONFLICT',
  STORAGE_ROOT_UNSAFE: 'STORAGE_ROOT_UNSAFE',
  WORKSPACE_INVENTORY_UNSAFE: 'WORKSPACE_INVENTORY_UNSAFE',
  LEASE_TAKEOVER_BLOCKED: 'LEASE_TAKEOVER_BLOCKED',
  CLEANUP_FAILED: 'CLEANUP_FAILED',
  SESSION_FINALIZATION_FAILED: 'SESSION_FINALIZATION_FAILED',
  PERSISTENCE_FAILED: 'PERSISTENCE_FAILED'
})

export class E3RecoveryError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options)
    this.name = 'E3RecoveryError'
    this.code = code
    this.details = Object.freeze({ ...details })
  }
}
