export const E3_REVIEW_ERROR = Object.freeze({
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INVALID_EVIDENCE: 'INVALID_EVIDENCE',
  INCOMPLETE_EVIDENCE: 'INCOMPLETE_EVIDENCE',
  FAILED_VALIDATION: 'FAILED_VALIDATION',
  HASH_BINDING_MISMATCH: 'HASH_BINDING_MISMATCH',
  ARTIFACT_TAMPERED: 'ARTIFACT_TAMPERED',
  SESSION_NOT_VALIDATING: 'SESSION_NOT_VALIDATING',
  STALE_SESSION: 'STALE_SESSION',
  LEASE_REQUIRED: 'LEASE_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  PERSISTENCE_FAILED: 'PERSISTENCE_FAILED'
})

export class E3ReviewError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options)
    this.name = 'E3ReviewError'
    this.code = code
    this.details = Object.freeze({ ...details })
  }
}
